# Introduction

Le présent rapport présente la méthodologie utilisée pour modéliser les niches climatiques et les distributions potentielles futures de 14 espèces fauniques en situation précaire. Le terme potentiel est utilisé, car l'estimation des aires de distributions futures qui seront effectivement occupées est une tâche beaucoup plus difficile. En effet, il faut tenir compte de plusieurs facteurs tels que les capacités de dispersion, les changements dans les habitats, les relations biotiques, etc. pour estimer ce qui sera effectivement utilisé. Le présent travail cherche plutôt à identifier les endroits qui deviendront favorables ou défavorables d'un point de vue climatique à la présence des espèces. En ce sens, on parlera plutôt de distributions potentielles des espèces en fonction des facteurs climatiques plutôt que de distributions réalisées.

La méthodologie proposée se base sur la modélisation de la distribution des espèces, une technique largement utilisée [depuis x ()]{style="background-color: #ffeb3b; padding: 0 0px;"}. Elle repose sur une approche en deux temps: les modèles sont d'abord construits à l'échelle de l'Amérique du Nord afin de prendre en compte la majeure partie de l'aire de répartition des espèces pour estimer le lien entre les variables climatiques et leur présence. Ces modèles de niches climatiques sont ensuite couplés à des modèles d'habitats à l'échelle de l'Amérique du Nord ou à plus fine échelle au Québec afin de considérer les habitats locaux et la disponibilité des données environnementales pour le territoire québécois. Deux approches sont également comparées afin de permettre plus de flexibilité au lien entre le climat et la présence des espèces. 

Les données d'occurrences utilisées proviennent de la base de données [Atlas](https://biodiversite-quebec.ca/fr/atlas) de [Biodiversité Québec](https://biodiversite-quebec.ca/fr), du _Global Biodiversity Information Facility_ (GBIF) [@gbiforg_gbif_2025] et de la plateforme [eBird](https://ebird.org/) [@cornell_lab_of_ornithology_ebird_2025]. Les données climatiques utilisées proviennent de l’ensemble de simulations ESPO-G6-R2 v1.0 produit par [Ouranos](https://www.ouranos.ca/fr) [@lavoie_ensemble_2024] [vérifier redondance]{style="background-color: #ffeb3b; padding: 0 0px;"}. Les projections climatiques futures sont réalisées pour trois scénarios d'émissions de gaz à effet de serre et deux horizons temporels, permettant ainsi d'évaluer les distributions potentielles futures de chaque espèce en fonction des changements climatiques probables. Différents résultats sont également présentés, notamment une évaluation des gains, des pertes et des changements potentiels dans les aires de répartition projetées.

<!-- 

Remerciements recommandés Ouranos: Données produites et publiées sur Portraits climatiques, le portail du Consortium Ouranos sur la climatologie régionale et l’adaptation aux changements climatiques 

Plus de détails? Ref pour les SDMs?

-->

