# Scénarios climatiques


Les scénarios climatiques utilisés proviennent des projections Ouranos de la réanalyse canadienne de surface de l'ensemble de simulations ESPO-G6-R2 v1.0 [@lavoie_ensemble_2024]. L’ensemble ESPO-G6-R2 v1.0 est disponible de 1950 à 2100 pour l’Amérique du Nord [https://www.ouranos.ca/fr/donnees-climatiques-ouranos/espo-g6-r2](https://www.ouranos.ca/fr/donnees-climatiques-ouranos/espo-g6-r2). La médiane de la température moyenne annuelle projetée d'un sous-ensemble de 15 modèles climatiques tirés de ESPO-G6-R2 v1.0 a été utilisé pour produire les aires de distributions projetées. La médiane a été utilisée pour limiter l'influence des valeurs potentiellement extrêmes de certains modèles climatique et pour suivre les directives sur l’appréciation et le traitement des risques liés
aux changements climatiques [@direction_de_ladaptation_aux_changements_adaptation_2026]. Bien qu'il est recommandé par Ouranos d'utiliser l'ensemble des modèles pour effectuer les projections d'aires de distributions et d'ensuite calculer la médiane ou la moyenne sur ces distributions projetées, nous avons plutôt précalculer la médiane des 15 modèles climatiques pour générer les distributions projetées afin les temps de calculs nécessaires. De plus, puisque l'incertitude associée aux modèles de distribution d'espèces est difficile à évaluer et que plusieurs éléments de sont pas pris en compte par la méthodologie (observations opportunistes, efforts d'observations très inégal, variables d'habitats limitées, capacités de dispersion non prise en compte), il a été jugé que le gain en évaluation de l'incertitude associée aux projections serait marginal par rapport à l'incertitude associée aux choix de méthodologie et à l'incertitude inhérente à la modélisation de la distribution des espèces.

Suivant les recommandations d'Ouranos [@ouranos_guide_2024] et les directives sur l'adaptation aux changements climatiques [@direction_de_ladaptation_aux_changements_adaptation_2026], trois scénarios d'émissions basés sur les trajectoires communes d’évolution socio-économique (SSP) jugés probables ou possibles ont été utilisés. Deux horizons temporels ont également été utilisés. 

:::: {layout-ncol=2}

::: {}
**Scénarios d'émission:**

- SSP2-4.5: Le milieu de la route (émissions modérées)
- SSP3-7.0: Rivalité régionale (émissions élevées)
- SSP5-8.5: Développement à base de combustiles fossiles (émissions très élevées)
:::

::: {}
**Horizons temporels:**

- 2041-2070: moyen terme
- 2071-2100: long terme
:::

::::

Les valeurs présentées sont les percentiles ou les moyennes des 15 modèles utilisés. ESPO-G6-R2 v1.0 est un ensemble de simulations climatiques multimodèles issues du Projet d’intercomparaison de modèles couplés (CMIP6). Un post-traitement par quantile avec conservation de la tendance est appliqué à cet ensemble climatique afin de réduire les biais et faire la mise à l’échelle statistique des sorties de modèles globaux. ESPO-G6-R2 v1.0 est composé de séries quotidiennes sur une échelle de 10X10 km pour trois variables : température maximale quotidienne, température minimale quotidienne et précipitation quotidienne. Les données des modèles climatiques globaux sont post-traitées en utilisant comme cible la Réanalyse Canadienne de Surface (RCaSv2.1) d’Environnement et Changement climatique Canada [@lavoie_ensemble_2024].



